// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.31.1
// source: common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户类型  主播类型：2、3、4、35、36
type USER_TYPE int32

const (
	USER_TYPE_UT_SUPERADMIN USER_TYPE = 0 //  超级管理员
	USER_TYPE_UT_NORMAL     USER_TYPE = 1 //  普通用户
)

// Enum value maps for USER_TYPE.
var (
	USER_TYPE_name = map[int32]string{
		0: "UT_SUPERADMIN",
		1: "UT_NORMAL",
	}
	USER_TYPE_value = map[string]int32{
		"UT_SUPERADMIN": 0,
		"UT_NORMAL":     1,
	}
)

func (x USER_TYPE) Enum() *USER_TYPE {
	p := new(USER_TYPE)
	*p = x
	return p
}

func (x USER_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (USER_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[0].Descriptor()
}

func (USER_TYPE) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[0]
}

func (x USER_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use USER_TYPE.Descriptor instead.
func (USER_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

// 性别类型
type SEX_TYPE int32

const (
	SEX_TYPE_ST_WOMAN SEX_TYPE = 0 // 女性
	SEX_TYPE_ST_MAN   SEX_TYPE = 1 // 男性
	SEX_TYPE_ST_OTHER SEX_TYPE = 2 // 不区分性别
)

// Enum value maps for SEX_TYPE.
var (
	SEX_TYPE_name = map[int32]string{
		0: "ST_WOMAN",
		1: "ST_MAN",
		2: "ST_OTHER",
	}
	SEX_TYPE_value = map[string]int32{
		"ST_WOMAN": 0,
		"ST_MAN":   1,
		"ST_OTHER": 2,
	}
)

func (x SEX_TYPE) Enum() *SEX_TYPE {
	p := new(SEX_TYPE)
	*p = x
	return p
}

func (x SEX_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SEX_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_common_common_proto_enumTypes[1].Descriptor()
}

func (SEX_TYPE) Type() protoreflect.EnumType {
	return &file_common_common_proto_enumTypes[1]
}

func (x SEX_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SEX_TYPE.Descriptor instead.
func (SEX_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

type HttpReplyCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HttpReplyCommon) Reset() {
	*x = HttpReplyCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpReplyCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpReplyCommon) ProtoMessage() {}

func (x *HttpReplyCommon) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpReplyCommon.ProtoReflect.Descriptor instead.
func (*HttpReplyCommon) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *HttpReplyCommon) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HttpReplyCommon) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 通用请求头
type BaseHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid   int64     `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`                           // 用户ID
	Appid    int32     `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`                             // 游戏ID
	Channel  int32     `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`                         // 渠道ID
	Version  string    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`                          // 版本号
	Region   string    `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                            // 区域
	Ext      string    `protobuf:"bytes,6,opt,name=ext,proto3" json:"ext,omitempty"`                                  // 扩展字段(json)
	UserType USER_TYPE `protobuf:"varint,8,opt,name=userType,proto3,enum=common.USER_TYPE" json:"userType,omitempty"` // 用户类型
	Gender   SEX_TYPE  `protobuf:"varint,9,opt,name=gender,proto3,enum=common.SEX_TYPE" json:"gender,omitempty"`      // 性别
}

func (x *BaseHead) Reset() {
	*x = BaseHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseHead) ProtoMessage() {}

func (x *BaseHead) ProtoReflect() protoreflect.Message {
	mi := &file_common_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseHead.ProtoReflect.Descriptor instead.
func (*BaseHead) Descriptor() ([]byte, []int) {
	return file_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *BaseHead) GetUserid() int64 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *BaseHead) GetAppid() int32 {
	if x != nil {
		return x.Appid
	}
	return 0
}

func (x *BaseHead) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *BaseHead) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *BaseHead) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *BaseHead) GetExt() string {
	if x != nil {
		return x.Ext
	}
	return ""
}

func (x *BaseHead) GetUserType() USER_TYPE {
	if x != nil {
		return x.UserType
	}
	return USER_TYPE_UT_SUPERADMIN
}

func (x *BaseHead) GetGender() SEX_TYPE {
	if x != nil {
		return x.Gender
	}
	return SEX_TYPE_ST_WOMAN
}

var File_common_common_proto protoreflect.FileDescriptor

var file_common_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x37, 0x0a,
	0x0f, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xef, 0x01, 0x0a, 0x08, 0x42, 0x61, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61,
	0x70, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x69,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x65, 0x78, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x78, 0x74, 0x12,
	0x2d, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28,
	0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x45, 0x58, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2a, 0x2d, 0x0a, 0x09, 0x55, 0x53, 0x45, 0x52,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x54, 0x5f, 0x53, 0x55, 0x50, 0x45,
	0x52, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x54, 0x5f, 0x4e,
	0x4f, 0x52, 0x4d, 0x41, 0x4c, 0x10, 0x01, 0x2a, 0x32, 0x0a, 0x08, 0x53, 0x45, 0x58, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x54, 0x5f, 0x57, 0x4f, 0x4d, 0x41, 0x4e, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x5f, 0x4d, 0x41, 0x4e, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x54, 0x5f, 0x4f, 0x54, 0x48, 0x45, 0x52, 0x10, 0x02, 0x42, 0x37, 0x5a, 0x35, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x65, 0x61, 0x66, 0x2d, 0x72,
	0x61, 0x69, 0x6e, 0x2f, 0x72, 0x61, 0x69, 0x6e, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x61, 0x64, 0x6d,
	0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x3b, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_common_proto_rawDescOnce sync.Once
	file_common_common_proto_rawDescData = file_common_common_proto_rawDesc
)

func file_common_common_proto_rawDescGZIP() []byte {
	file_common_common_proto_rawDescOnce.Do(func() {
		file_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_common_proto_rawDescData)
	})
	return file_common_common_proto_rawDescData
}

var file_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_common_proto_goTypes = []any{
	(USER_TYPE)(0),          // 0: common.USER_TYPE
	(SEX_TYPE)(0),           // 1: common.SEX_TYPE
	(*HttpReplyCommon)(nil), // 2: common.HttpReplyCommon
	(*BaseHead)(nil),        // 3: common.BaseHead
}
var file_common_common_proto_depIdxs = []int32{
	0, // 0: common.BaseHead.userType:type_name -> common.USER_TYPE
	1, // 1: common.BaseHead.gender:type_name -> common.SEX_TYPE
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_common_proto_init() }
func file_common_common_proto_init() {
	if File_common_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*HttpReplyCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BaseHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_common_proto_goTypes,
		DependencyIndexes: file_common_common_proto_depIdxs,
		EnumInfos:         file_common_common_proto_enumTypes,
		MessageInfos:      file_common_common_proto_msgTypes,
	}.Build()
	File_common_common_proto = out.File
	file_common_common_proto_rawDesc = nil
	file_common_common_proto_goTypes = nil
	file_common_common_proto_depIdxs = nil
}
