GrpcAddr: 192.168.31.100:8090
Version: "v0.0.1"
Mode: "test"
LogConfig:
  level: "debug"
  caller: true
  writer: "console"
  encode: "json"
CKConfig:
  hosts:
    -
      - "127.0.0.1:9000"
  DB: "test"
  username: "root"
  password: "yeyangfengqi"
