// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package infrastructure

import (
	"github.com/leaf-rain/raindata/app_report/internal/infrastructure/config"
	"github.com/leaf-rain/raindata/app_report/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*Infrastructure, error) {
	cmdArgs := config.NewCmdArgs()
	configConfig, err := config.InitConfig(cmdArgs)
	if err != nil {
		return nil, err
	}
	logConfig := config.GetLogCfgByConfig(configConfig)
	zapLogger := logger.InitLogger(logConfig)
	infrastructure := NewInfrastructure(zapLogger)
	return infrastructure, nil
}

// wire.go:

var WireInfrastructureSet = wire.NewSet(config.NewCmdArgs, config.InitConfig, config.GetLogCfgByConfig, logger.InitLogger, NewInfrastructure)
