// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: bi/v1/method.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bi_Ping_FullMethodName = "/bi.v1.Bi/Ping"
)

// BiClient is the client API for Bi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The greeting service definition.
type BiClient interface {
	// Sends a greeting
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongReply, error)
}

type biClient struct {
	cc grpc.ClientConnInterface
}

func NewBiClient(cc grpc.ClientConnInterface) BiClient {
	return &biClient{cc}
}

func (c *biClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PongReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PongReply)
	err := c.cc.Invoke(ctx, Bi_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BiServer is the server API for Bi service.
// All implementations must embed UnimplementedBiServer
// for forward compatibility.
//
// The greeting service definition.
type BiServer interface {
	// Sends a greeting
	Ping(context.Context, *PingRequest) (*PongReply, error)
	mustEmbedUnimplementedBiServer()
}

// UnimplementedBiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBiServer struct{}

func (UnimplementedBiServer) Ping(context.Context, *PingRequest) (*PongReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBiServer) mustEmbedUnimplementedBiServer() {}
func (UnimplementedBiServer) testEmbeddedByValue()            {}

// UnsafeBiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BiServer will
// result in compilation errors.
type UnsafeBiServer interface {
	mustEmbedUnimplementedBiServer()
}

func RegisterBiServer(s grpc.ServiceRegistrar, srv BiServer) {
	// If the following call pancis, it indicates UnimplementedBiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bi_ServiceDesc, srv)
}

func _Bi_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BiServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bi_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BiServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bi_ServiceDesc is the grpc.ServiceDesc for Bi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bi.v1.Bi",
	HandlerType: (*BiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Bi_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bi/v1/method.proto",
}
