// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.31.1
// source: rmongo/mongo.proto

package rmongo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MongoCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url              string `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
	Db               string `protobuf:"bytes,2,opt,name=Db,proto3" json:"Db,omitempty"`
	MaxPoolSize      uint64 `protobuf:"varint,3,opt,name=MaxPoolSize,proto3" json:"MaxPoolSize,omitempty"`
	MinPoolSize      uint64 `protobuf:"varint,4,opt,name=MinPoolSize,proto3" json:"MinPoolSize,omitempty"`
	MaxIdleTimeMS    uint64 `protobuf:"varint,5,opt,name=MaxIdleTimeMS,proto3" json:"MaxIdleTimeMS,omitempty"`
	ConnectTimeoutMS int64  `protobuf:"varint,7,opt,name=ConnectTimeoutMS,proto3" json:"ConnectTimeoutMS,omitempty"`
}

func (x *MongoCfg) Reset() {
	*x = MongoCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rmongo_mongo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MongoCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoCfg) ProtoMessage() {}

func (x *MongoCfg) ProtoReflect() protoreflect.Message {
	mi := &file_rmongo_mongo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoCfg.ProtoReflect.Descriptor instead.
func (*MongoCfg) Descriptor() ([]byte, []int) {
	return file_rmongo_mongo_proto_rawDescGZIP(), []int{0}
}

func (x *MongoCfg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MongoCfg) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *MongoCfg) GetMaxPoolSize() uint64 {
	if x != nil {
		return x.MaxPoolSize
	}
	return 0
}

func (x *MongoCfg) GetMinPoolSize() uint64 {
	if x != nil {
		return x.MinPoolSize
	}
	return 0
}

func (x *MongoCfg) GetMaxIdleTimeMS() uint64 {
	if x != nil {
		return x.MaxIdleTimeMS
	}
	return 0
}

func (x *MongoCfg) GetConnectTimeoutMS() int64 {
	if x != nil {
		return x.ConnectTimeoutMS
	}
	return 0
}

var File_rmongo_mongo_proto protoreflect.FileDescriptor

var file_rmongo_mongo_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x22, 0xc2, 0x01, 0x0a,
	0x08, 0x4d, 0x6f, 0x6e, 0x67, 0x6f, 0x43, 0x66, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x44,
	0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x44, 0x62, 0x12, 0x20, 0x0a, 0x0b, 0x4d,
	0x61, 0x78, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x4d, 0x61, 0x78, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x4d, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x4d, 0x69, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12,
	0x24, 0x0a, 0x0d, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x6c, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x53,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x4d, 0x61, 0x78, 0x49, 0x64, 0x6c, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x4d, 0x53, 0x12, 0x2a, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d, 0x53, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x10, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x4d,
	0x53, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6c, 0x65, 0x61, 0x66, 0x2d, 0x72, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x61, 0x69, 0x6e, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x6d, 0x6f, 0x6e, 0x67, 0x6f,
	0x3b, 0x72, 0x6d, 0x6f, 0x6e, 0x67, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rmongo_mongo_proto_rawDescOnce sync.Once
	file_rmongo_mongo_proto_rawDescData = file_rmongo_mongo_proto_rawDesc
)

func file_rmongo_mongo_proto_rawDescGZIP() []byte {
	file_rmongo_mongo_proto_rawDescOnce.Do(func() {
		file_rmongo_mongo_proto_rawDescData = protoimpl.X.CompressGZIP(file_rmongo_mongo_proto_rawDescData)
	})
	return file_rmongo_mongo_proto_rawDescData
}

var file_rmongo_mongo_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rmongo_mongo_proto_goTypes = []any{
	(*MongoCfg)(nil), // 0: rmongo.MongoCfg
}
var file_rmongo_mongo_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rmongo_mongo_proto_init() }
func file_rmongo_mongo_proto_init() {
	if File_rmongo_mongo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rmongo_mongo_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*MongoCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rmongo_mongo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rmongo_mongo_proto_goTypes,
		DependencyIndexes: file_rmongo_mongo_proto_depIdxs,
		MessageInfos:      file_rmongo_mongo_proto_msgTypes,
	}.Build()
	File_rmongo_mongo_proto = out.File
	file_rmongo_mongo_proto_rawDesc = nil
	file_rmongo_mongo_proto_goTypes = nil
	file_rmongo_mongo_proto_depIdxs = nil
}
