// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/leaf-rain/raindata/admin/internal/biz"
	"github.com/leaf-rain/raindata/admin/internal/conf"
	"github.com/leaf-rain/raindata/admin/internal/data"
	"github.com/leaf-rain/raindata/admin/internal/server"
	"github.com/leaf-rain/raindata/admin/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepoI := data.NewAuthRepo(dataData)
	authBiz := biz.NewAuthBiz(confData, authRepoI, logger)
	authService := service.NewAuthService(logger, confData, authBiz)
	grpcServer := server.NewGRPCServer(confServer, authService, logger)
	httpServer := server.NewHTTPServer(confServer, authBiz, authService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
