// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"github.com/google/wire"
	"github.com/leaf-rain/raindata/app_basicsdata/internal/domain"
	"github.com/leaf-rain/raindata/app_basicsdata/internal/infrastructure/config"
	"github.com/leaf-rain/raindata/app_basicsdata/internal/infrastructure/entity"
	"github.com/leaf-rain/raindata/app_report/pkg/logger"
	"github.com/leaf-rain/raindata/common/rclickhouse"
	"github.com/leaf-rain/raindata/common/retcd"
)

// Injectors from wire.go:

func Initialize() (*Applications, error) {
	cmdArgs := config.NewCmdArgs()
	configConfig, err := config.InitConfig(cmdArgs)
	if err != nil {
		return nil, err
	}
	logConfig := config.GetLogCfgByConfig(configConfig)
	zapLogger := logger.InitLogger(logConfig)
	context := config.GetCtx(configConfig)
	etcdConfig := config.GetEtcdConfig(configConfig)
	client, err := retcd.NewEtcdClient(etcdConfig, zapLogger)
	if err != nil {
		return nil, err
	}
	clickhouseConfig := config.GetClickhouseConfig(configConfig)
	clickhouse, err := rclickhouse.NewClickhouse(clickhouseConfig)
	if err != nil {
		return nil, err
	}
	repository, err := entity.NewRepository(context, client, clickhouse, zapLogger, configConfig)
	if err != nil {
		return nil, err
	}
	metadata, err := domain.NewMetadata(zapLogger, repository, configConfig, client, clickhouse)
	if err != nil {
		return nil, err
	}
	appMetadata := NewAppMetadata(zapLogger, configConfig, metadata)
	applications := NewApplications(zapLogger, appMetadata)
	return applications, nil
}

// wire.go:

var WireApplicationSet = wire.NewSet(
	NewAppMetadata,
	NewApplications,
)
