// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package domain

import (
	"github.com/leaf-rain/raindata/app_report/internal/infrastructure/config"
	"github.com/leaf-rain/raindata/app_report/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*Domain, error) {
	cmdArgs := config.NewCmdArgs()
	configConfig, err := config.InitConfig(cmdArgs)
	if err != nil {
		return nil, err
	}
	logConfig := config.GetLogCfgByConfig(configConfig)
	zapLogger := logger.InitLogger(logConfig)
	ckWriter := NewCkWriter(zapLogger)
	eventManager := NewEventManager(zapLogger)
	domain := NewDomain(zapLogger, ckWriter, eventManager)
	return domain, nil
}

// wire.go:

var WireDomainSet = wire.NewSet(
	NewCkWriter,
	NewEventManager,
	NewDomain,
)
