GrpcAddr: 192.168.10.28:8090
Version: "v0.0.1"
Mode: "test"
MetadataPath: "/raindata/metadata"
LogConfig:
  level: "debug"
  caller: true
  writer: "console"
  encode: "json"
  logFile:
    maxSize: 100
    output:
      - "logs"
EtcdConfig:
  Endpoints:
    - "192.168.10.28:2379"
ClickhouseConfig:
  hosts:
    -
      - "127.0.0.1:9000"
  username: "root"
  password: "yeyangfengqi"
  DB: "test"
  debug: "true"
  protocol: "http"