server:
  http:
    addr: "0.0.0.0:9000"
    timeout:
      seconds: 5
  grpc:
    addr: "0.0.0.0:9001"
    timeout:
      seconds: 5
data:
  database:
    driverName: "mysql"
    dbSource: "root:yeyangfengqi@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local"
    maxOpenConns: 6
    maxIdleConns: 4
    idleTimeOut: 10
    debug: false

  redis:
    poolSize: 4
    addr:
      - "127.0.0.1:6379"
    read_timeout: 2
    write_timeout: 2
log:
  server_name: "app_bi"
  appid: "1"
  log_level: "debug"
