server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driverName: mysql
    dbSource: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
    maxOpenConns: 6
    maxIdleConns: 4
    idleTimeOut: 10
    debug: false

  redis:
    poolSize: 4
    addr:
      - 127.0.0.1:6379
    read_timeout: 2
    write_timeout: 2
log:
  server_name: app_bi
  appid: 1
  log_level: "debug"
