server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 1s
    write_timeout: 1s
  jwt:
    secret: "123456"