// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v6.31.1
// source: rredis/redis.proto

package rredis

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedisCfg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoolSize     uint64   `protobuf:"varint,1,opt,name=PoolSize,proto3" json:"PoolSize,omitempty"`
	Addr         []string `protobuf:"bytes,2,rep,name=Addr,proto3" json:"Addr,omitempty"`
	Pwd          string   `protobuf:"bytes,3,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	DialTimeout  int64    `protobuf:"varint,4,opt,name=DialTimeout,proto3" json:"DialTimeout,omitempty"`
	ReadTimeout  int64    `protobuf:"varint,5,opt,name=ReadTimeout,proto3" json:"ReadTimeout,omitempty"`
	WriteTimeout int64    `protobuf:"varint,6,opt,name=WriteTimeout,proto3" json:"WriteTimeout,omitempty"`
	DB           int64    `protobuf:"varint,7,opt,name=DB,proto3" json:"DB,omitempty"`
}

func (x *RedisCfg) Reset() {
	*x = RedisCfg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rredis_redis_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedisCfg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisCfg) ProtoMessage() {}

func (x *RedisCfg) ProtoReflect() protoreflect.Message {
	mi := &file_rredis_redis_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisCfg.ProtoReflect.Descriptor instead.
func (*RedisCfg) Descriptor() ([]byte, []int) {
	return file_rredis_redis_proto_rawDescGZIP(), []int{0}
}

func (x *RedisCfg) GetPoolSize() uint64 {
	if x != nil {
		return x.PoolSize
	}
	return 0
}

func (x *RedisCfg) GetAddr() []string {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *RedisCfg) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *RedisCfg) GetDialTimeout() int64 {
	if x != nil {
		return x.DialTimeout
	}
	return 0
}

func (x *RedisCfg) GetReadTimeout() int64 {
	if x != nil {
		return x.ReadTimeout
	}
	return 0
}

func (x *RedisCfg) GetWriteTimeout() int64 {
	if x != nil {
		return x.WriteTimeout
	}
	return 0
}

func (x *RedisCfg) GetDB() int64 {
	if x != nil {
		return x.DB
	}
	return 0
}

var File_rredis_redis_proto protoreflect.FileDescriptor

var file_rredis_redis_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2f, 0x72, 0x65, 0x64, 0x69, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x72, 0x65, 0x64, 0x69, 0x73, 0x22, 0xc4, 0x01, 0x0a,
	0x08, 0x52, 0x65, 0x64, 0x69, 0x73, 0x43, 0x66, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6f, 0x6f,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x50, 0x6f, 0x6f,
	0x6c, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x77, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x77, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x44,
	0x69, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0b, 0x44, 0x69, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x20, 0x0a,
	0x0b, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x52, 0x65, 0x61, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12,
	0x22, 0x0a, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x57, 0x72, 0x69, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x6f, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x44, 0x42, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x44, 0x42, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x65, 0x61, 0x66, 0x2d, 0x72, 0x61, 0x69, 0x6e, 0x2f, 0x72, 0x61, 0x69, 0x6e,
	0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x72, 0x72, 0x65, 0x64,
	0x69, 0x73, 0x3b, 0x72, 0x72, 0x65, 0x64, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rredis_redis_proto_rawDescOnce sync.Once
	file_rredis_redis_proto_rawDescData = file_rredis_redis_proto_rawDesc
)

func file_rredis_redis_proto_rawDescGZIP() []byte {
	file_rredis_redis_proto_rawDescOnce.Do(func() {
		file_rredis_redis_proto_rawDescData = protoimpl.X.CompressGZIP(file_rredis_redis_proto_rawDescData)
	})
	return file_rredis_redis_proto_rawDescData
}

var file_rredis_redis_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rredis_redis_proto_goTypes = []any{
	(*RedisCfg)(nil), // 0: rredis.RedisCfg
}
var file_rredis_redis_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rredis_redis_proto_init() }
func file_rredis_redis_proto_init() {
	if File_rredis_redis_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rredis_redis_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RedisCfg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rredis_redis_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rredis_redis_proto_goTypes,
		DependencyIndexes: file_rredis_redis_proto_depIdxs,
		MessageInfos:      file_rredis_redis_proto_msgTypes,
	}.Build()
	File_rredis_redis_proto = out.File
	file_rredis_redis_proto_rawDesc = nil
	file_rredis_redis_proto_goTypes = nil
	file_rredis_redis_proto_depIdxs = nil
}
