// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"github.com/leaf-rain/raindata/app_report/internal/domain"
	"github.com/leaf-rain/raindata/app_report/internal/infrastructure/config"
	"github.com/leaf-rain/raindata/app_report/pkg/logger"
	"github.com/google/wire"
)

// Injectors from wire.go:

func Initialize() (*Applications, error) {
	cmdArgs := config.NewCmdArgs()
	configConfig, err := config.InitConfig(cmdArgs)
	if err != nil {
		return nil, err
	}
	logConfig := config.GetLogCfgByConfig(configConfig)
	zapLogger := logger.InitLogger(logConfig)
	eventManager := domain.NewEventManager(zapLogger)
	ckWriter := domain.NewCkWriter(zapLogger)
	appStream := NewAppStream(zapLogger, configConfig, eventManager, ckWriter)
	applications := NewApplications(zapLogger, appStream)
	return applications, nil
}

// wire.go:

var WireApplicationSet = wire.NewSet(
	NewAppStream,
	NewApplications,
)
